# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1201)),
                ('slugf', models.SlugField(unique=True)),
                ('content', models.TextField(max_length=1230)),
                ('fimage', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
